import Head from 'next/head'

export default function CustomHead() {
  return (
    <div>
      <Head>
        <title>Extenders Charity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/logo.jpeg" />
      </Head>
</div>
  )
}
